services:
  kepegawaian:
    container_name: kepegawain-fe
    image: kepegawaian-fe:latest
    build: .
    env_file:
      - .env
    entrypoint: 
      - node
      - server.js
    ports:
      - 3002:3000