/**
 * shared/enums — enum & union types lintas-domain
 *
 * Dipakai oleh >= 2 module. Semua tipe di sini di-generate dari OpenAPI spec
 * oleh docs/api/extract-types.js.
 */

/** Semua status HTTP (dipakai oleh field statusText di wrapper response). */
export type HttpStatusText =
	| "100 CONTINUE"
	| "101 SWITCHING_PROTOCOLS"
	| "102 PROCESSING"
	| "103 EARLY_HINTS"
	| "200 OK"
	| "201 CREATED"
	| "202 ACCEPTED"
	| "203 NON_AUTHORITATIVE_INFORMATION"
	| "204 NO_CONTENT"
	| "205 RESET_CONTENT"
	| "206 PARTIAL_CONTENT"
	| "207 MULTI_STATUS"
	| "208 ALREADY_REPORTED"
	| "226 IM_USED"
	| "300 MULTIPLE_CHOICES"
	| "301 MOVED_PERMANENTLY"
	| "302 FOUND"
	| "303 SEE_OTHER"
	| "304 NOT_MODIFIED"
	| "307 TEMPORARY_REDIRECT"
	| "308 PERMANENT_REDIRECT"
	| "400 BAD_REQUEST"
	| "401 UNAUTHORIZED"
	| "402 PAYMENT_REQUIRED"
	| "403 FORBIDDEN"
	| "404 NOT_FOUND"
	| "405 METHOD_NOT_ALLOWED"
	| "406 NOT_ACCEPTABLE"
	| "407 PROXY_AUTHENTICATION_REQUIRED"
	| "408 REQUEST_TIMEOUT"
	| "409 CONFLICT"
	| "410 GONE"
	| "411 LENGTH_REQUIRED"
	| "412 PRECONDITION_FAILED"
	| "413 CONTENT_TOO_LARGE"
	| "413 PAYLOAD_TOO_LARGE"
	| "414 URI_TOO_LONG"
	| "415 UNSUPPORTED_MEDIA_TYPE"
	| "416 REQUESTED_RANGE_NOT_SATISFIABLE"
	| "417 EXPECTATION_FAILED"
	| "418 I_AM_A_TEAPOT"
	| "421 MISDIRECTED_REQUEST"
	| "422 UNPROCESSABLE_CONTENT"
	| "422 UNPROCESSABLE_ENTITY"
	| "423 LOCKED"
	| "424 FAILED_DEPENDENCY"
	| "425 TOO_EARLY"
	| "426 UPGRADE_REQUIRED"
	| "428 PRECONDITION_REQUIRED"
	| "429 TOO_MANY_REQUESTS"
	| "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
	| "451 UNAVAILABLE_FOR_LEGAL_REASONS"
	| "500 INTERNAL_SERVER_ERROR"
	| "501 NOT_IMPLEMENTED"
	| "502 BAD_GATEWAY"
	| "503 SERVICE_UNAVAILABLE"
	| "504 GATEWAY_TIMEOUT"
	| "505 HTTP_VERSION_NOT_SUPPORTED"
	| "506 VARIANT_ALSO_NEGOTIATES"
	| "507 INSUFFICIENT_STORAGE"
	| "508 LOOP_DETECTED"
	| "509 BANDWIDTH_LIMIT_EXCEEDED"
	| "510 NOT_EXTENDED"
	| "511 NETWORK_AUTHENTICATION_REQUIRED";

/** Jenis SK kepegawaian (SK_KENAIKAN_PANGKAT_GOLONGAN, SK_CAPEG, SK_PEGAWAI_TETAP, dll). */
export type JenisSk =
	| "SK_KENAIKAN_PANGKAT_GOLONGAN"
	| "SK_CAPEG"
	| "SK_PEGAWAI_TETAP"
	| "SK_JABATAN"
	| "SK_MUTASI"
	| "SK_PENSIUN"
	| "SK_LAINNYA"
	| "SK_PENYESUAIAN_GAJI"
	| "SK_KENAIKAN_GAJI_BERKALA";

/** Jenis kelamin (LAKI_LAKI, PEREMPUAN). */
export type JenisKelamin = "LAKI_LAKI" | "PEREMPUAN";

/** Agama (ISLAM, KRISTEN, KATOLIK, HINDU, BUDHA). */
export type Agama =
	| "TIDAK_TAHU"
	| "ISLAM"
	| "KRISTEN"
	| "KATOLIK"
	| "HINDU"
	| "BUDHA"
	| "KONGHUCHU"
	| "ALIRAN_KEPERCAYAAN"
	| "LAINNYA";

/** Status kepegawaian (KONTRAK, CAPEG, PEGAWAI, CALON_HONORER, HONORER, NON_PEGAWAI). */
export type StatusKepegawaian = "KONTRAK" | "CAPEG" | "PEGAWAI" | "CALON_HONORER" | "HONORER" | "NON_PEGAWAI";

/** Status perkawinan (BELUM_KAWIN, KAWIN, JANDA_DUDA, MENIKAH_SEKANTOR, TIDAK_TAHU). */
export type StatusKawin = "BELUM_KAWIN" | "KAWIN" | "JANDA_DUDA" | "MENIKAH_SEKANTOR" | "TIDAK_TAHU";

/** Golongan darah (A, B, AB, O). */
export type GolonganDarah = "A" | "B" | "AB" | "O";

/** Jenis profil yang diupdate (PROFIL_KELUARGA, PROFIL_PENDIDIKAN). */
export type JenisProfilUpdate =
	| "PROFIL_KELUARGA"
	| "PROFIL_PENDIDIKAN"
	| "PROFIL_PELATIHAN"
	| "PROFIL_KEAHLIAN"
	| "FOTO_PROFIL"
	| "KARTU_IDENTITAS"
	| "PROFIL_PENGALAMAN_KERJA";

/** Tipe komponen penggajian (NONE, PEMASUKAN, POTONGAN). */
export type TipeKomponen = "NONE" | "PEMASUKAN" | "POTONGAN";

/** Status approval umum (PENDING, APPROVED, CONFIRMED, REJECTED, CANCELED, RETURNED). */
export type StatusApproval = "PENDING" | "APPROVED" | "CONFIRMED" | "REJECTED" | "CANCELED" | "RETURNED";

/** Status berhenti pegawai (BERHENTI_OR_KELUAR, DIRUMAHKAN). */
export type StatusBerhenti =
	| "BERHENTI_OR_KELUAR"
	| "DIRUMAHKAN"
	| "KARYAWAN_AKTIF"
	| "LAMARAN_BARU"
	| "TAHAP_SELEKSI"
	| "DITERIMA"
	| "DIREKOMENDASIKAN"
	| "DITOLAK";

/** Tingkat kemampuan keahlian (KURANG, BAIK, CUKUP). */
export type TingkatKemampuan = "KURANG" | "BAIK" | "CUKUP";

/** Hubungan keluarga (SUAMI, ISTRI, AYAH, IBU, ANAK, SAUDARA). */
export type HubunganKeluarga = "SUAMI" | "ISTRI" | "AYAH" | "IBU" | "ANAK" | "SAUDARA";

/** Status pendidikan anggota keluarga (BELUM_SEKOLAH, SEKOLAH, SELESAI_SEKOLAH). */
export type StatusPendidikanKeluarga = "BELUM_SEKOLAH" | "SEKOLAH" | "SELESAI_SEKOLAH";
